import type { EndpointDefinition } from "./types";

/**
 * Full registry of every API-Football v3 endpoint (38 total, per api-football.com/documentation-v3),
 * annotated with how the agent should treat each one: how volatile the data is (tier), how long a
 * cached response stays fresh, whether the vendor itself publishes a "recommended calls per day"
 * figure, and a priority used to decide what to sacrifice first when the daily budget runs low.
 *
 * This registry is the single source of truth the quota manager, cache and planner all read from —
 * change caching/priority behaviour here, not in the call sites.
 */
export const ENDPOINTS: EndpointDefinition[] = [
  // ---- Meta -----------------------------------------------------------
  {
    key: "status",
    category: "meta",
    path: "/status",
    description: "Current account status: plan, requests used/remaining today, subscription end date.",
    params: [],
    tier: "static",
    cacheTtlSeconds: 6 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 5,
  },
  {
    key: "timezone",
    category: "meta",
    path: "/timezone",
    description: "All valid timezone strings accepted by the `timezone` parameter on other endpoints.",
    params: [],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
  {
    key: "countries",
    category: "meta",
    path: "/countries",
    description: "Countries available for the `leagues` endpoint.",
    params: [
      { name: "name", description: "Country name" },
      { name: "code", description: "2-letter ISO country code" },
      { name: "search", description: ">=3 char search string" },
    ],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },

  // ---- Leagues ----------------------------------------------------------
  {
    key: "leagues",
    category: "leagues",
    path: "/leagues",
    description: "Leagues & cups, including per-season `coverage` flags (what data is actually available for that competition).",
    params: [
      { name: "id", description: "League id" },
      { name: "name", description: "League name" },
      { name: "country", description: "Country name" },
      { name: "code", description: "Country code" },
      { name: "season", description: "4-digit season" },
      { name: "team", description: "Team id" },
      { name: "type", description: "league or cup" },
      { name: "current", description: "true/false, only the current season" },
      { name: "search", description: ">=3 char search string" },
      { name: "last", description: "Last N leagues added" },
    ],
    tier: "static",
    cacheTtlSeconds: 7 * 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 2,
  },
  {
    key: "leagues.seasons",
    category: "leagues",
    path: "/leagues/seasons",
    description: "All season years the API has ever indexed.",
    params: [],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },

  // ---- Teams --------------------------------------------------------------
  {
    key: "teams",
    category: "teams",
    path: "/teams",
    description: "Team profiles (id, name, logo, venue) filterable by league/season/country/name.",
    params: [
      { name: "id", description: "Team id" },
      { name: "name", description: "Team name" },
      { name: "league", description: "League id" },
      { name: "season", description: "4-digit season" },
      { name: "country", description: "Country name" },
      { name: "code", description: "3-letter team code" },
      { name: "venue", description: "Venue id" },
      { name: "search", description: ">=3 char search string" },
    ],
    tier: "semi-static",
    cacheTtlSeconds: 7 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 2,
  },
  {
    key: "teams.statistics",
    category: "teams",
    path: "/teams/statistics",
    description: "A team's aggregated stats (form, goals for/against, streaks) for one league+season.",
    params: [
      { name: "league", required: true, description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
      { name: "team", required: true, description: "Team id" },
      { name: "date", description: "Stats up to this date" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 6 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 3,
  },
  {
    key: "teams.seasons",
    category: "teams",
    path: "/teams/seasons",
    description: "Seasons for which a given team has data.",
    params: [{ name: "team", required: true, description: "Team id" }],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
  {
    key: "teams.countries",
    category: "teams",
    path: "/teams/countries",
    description: "Countries available for the `teams` endpoint.",
    params: [],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },

  // ---- Venues ---------------------------------------------------------------
  {
    key: "venues",
    category: "venues",
    path: "/venues",
    description: "Stadium/venue profiles (capacity, city, surface).",
    params: [
      { name: "id", description: "Venue id" },
      { name: "name", description: "Venue name" },
      { name: "city", description: "City" },
      { name: "country", description: "Country name" },
      { name: "search", description: ">=3 char search string" },
    ],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },

  // ---- Standings ------------------------------------------------------------
  {
    key: "standings",
    category: "standings",
    path: "/standings",
    description: "League table(s) for a league+season, including group/stage splits where relevant.",
    params: [
      { name: "league", required: true, description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
      { name: "team", description: "Restrict to one team's row" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 3 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 4,
  },

  // ---- Fixtures ---------------------------------------------------------------
  {
    key: "fixtures.live",
    category: "fixtures",
    path: "/fixtures",
    description: "All fixtures currently live worldwide (call with live=all). The single most efficient way to track every in-progress match in one request.",
    params: [{ name: "live", description: "'all' or comma-separated league ids" }],
    tier: "live",
    cacheTtlSeconds: 60,
    vendorRecommendedCallsPerDay: null,
    priority: 5,
  },
  {
    key: "fixtures.list",
    category: "fixtures",
    path: "/fixtures",
    description: "Fixtures by id(s), date, date range, league+season, team, round or status (not the live shortcut).",
    params: [
      { name: "id", description: "Fixture id" },
      { name: "ids", description: "Up to 20 fixture ids" },
      { name: "date", description: "YYYY-MM-DD" },
      { name: "league", description: "League id" },
      { name: "season", description: "4-digit season" },
      { name: "team", description: "Team id" },
      { name: "last", description: "Last N fixtures, <=2 digits" },
      { name: "next", description: "Next N fixtures, <=2 digits" },
      { name: "from", description: "YYYY-MM-DD" },
      { name: "to", description: "YYYY-MM-DD" },
      { name: "round", description: "Round name" },
      { name: "status", description: "e.g. NS, FT, NS-FT-CANC" },
      { name: "venue", description: "Venue id" },
      { name: "timezone", description: "A valid timezone from /timezone" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 4,
  },
  {
    key: "fixtures.rounds",
    category: "fixtures",
    path: "/fixtures/rounds",
    description: "Round names for a league+season (e.g. 'Regular Season - 12').",
    params: [
      { name: "league", required: true, description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
      { name: "current", description: "true/false" },
      { name: "dates", description: "true/false, include round dates" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 2,
  },
  {
    key: "fixtures.headtohead",
    category: "fixtures",
    path: "/fixtures/headtohead",
    description: "Historical fixtures between two teams.",
    params: [
      { name: "h2h", required: true, description: "'teamId-teamId'" },
      { name: "date", description: "YYYY-MM-DD" },
      { name: "league", description: "League id" },
      { name: "season", description: "4-digit season" },
      { name: "last", description: "Last N" },
      { name: "next", description: "Next N" },
      { name: "from", description: "YYYY-MM-DD" },
      { name: "to", description: "YYYY-MM-DD" },
      { name: "status", description: "Fixture status short code(s)" },
      { name: "venue", description: "Venue id" },
      { name: "timezone", description: "A valid timezone" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 3,
  },
  {
    key: "fixtures.statistics",
    category: "fixtures",
    path: "/fixtures/statistics",
    description: "Shots, possession, corners etc. for one fixture.",
    params: [
      { name: "fixture", required: true, description: "Fixture id" },
      { name: "team", description: "Restrict to one team" },
      { name: "type", description: "Restrict to one stat type" },
      { name: "half", description: "true/false, split by half" },
    ],
    tier: "live",
    cacheTtlSeconds: 300,
    vendorRecommendedCallsPerDay: null,
    priority: 3,
  },
  {
    key: "fixtures.events",
    category: "fixtures",
    path: "/fixtures/events",
    description: "Goals, cards, substitutions and VAR events for one fixture, in order.",
    params: [
      { name: "fixture", required: true, description: "Fixture id" },
      { name: "team", description: "Restrict to one team" },
      { name: "player", description: "Restrict to one player" },
      { name: "type", description: "Restrict to one event type" },
    ],
    tier: "live",
    cacheTtlSeconds: 60,
    vendorRecommendedCallsPerDay: null,
    priority: 4,
  },
  {
    key: "fixtures.lineups",
    category: "fixtures",
    path: "/fixtures/lineups",
    description: "Starting XI, formation, substitutes and coach for one fixture. Only available 20-40 min before kickoff onward.",
    params: [
      { name: "fixture", required: true, description: "Fixture id" },
      { name: "team", description: "Restrict to one team" },
      { name: "player", description: "Restrict to one player" },
      { name: "type", description: "'lineup' or 'startXI'" },
    ],
    tier: "live",
    cacheTtlSeconds: 300,
    vendorRecommendedCallsPerDay: null,
    priority: 3,
  },
  {
    key: "fixtures.players",
    category: "fixtures",
    path: "/fixtures/players",
    description: "Per-player statistics (rating, shots, passes, duels) for one fixture.",
    params: [
      { name: "fixture", required: true, description: "Fixture id" },
      { name: "team", description: "Restrict to one team" },
    ],
    tier: "live",
    cacheTtlSeconds: 300,
    vendorRecommendedCallsPerDay: null,
    priority: 2,
  },

  // ---- Injuries -----------------------------------------------------------------
  {
    key: "injuries",
    category: "injuries",
    path: "/injuries",
    description: "Players unavailable (injured/suspended) filterable by league, team, player or fixture.",
    params: [
      { name: "league", description: "League id" },
      { name: "season", description: "Required alongside league/team/player" },
      { name: "fixture", description: "Fixture id" },
      { name: "team", description: "Team id" },
      { name: "player", description: "Player id" },
      { name: "date", description: "YYYY-MM-DD" },
      { name: "timezone", description: "A valid timezone" },
    ],
    tier: "semi-static",
    cacheTtlSeconds: 12 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 2,
  },

  // ---- Predictions ----------------------------------------------------------------
  {
    key: "predictions",
    category: "predictions",
    path: "/predictions",
    description: "Model prediction (winner, goals, comparison) for one upcoming fixture. Fixed once computed pre-match.",
    params: [{ name: "fixture", required: true, description: "Fixture id" }],
    tier: "scheduled",
    cacheTtlSeconds: 12 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 3,
  },

  // ---- Coachs -----------------------------------------------------------------------
  {
    key: "coachs",
    category: "coachs",
    path: "/coachs",
    description: "Coach profile and career history.",
    params: [
      { name: "id", description: "Coach id" },
      { name: "team", description: "Team id" },
      { name: "search", description: ">=3 char search string" },
    ],
    tier: "semi-static",
    cacheTtlSeconds: 7 * 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 1,
  },

  // ---- Players ------------------------------------------------------------------------
  {
    key: "players",
    category: "players",
    path: "/players",
    description: "Player profile + season statistics; requires league+season or team+season.",
    params: [
      { name: "id", description: "Player id" },
      { name: "team", description: "Team id" },
      { name: "league", description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
      { name: "search", description: ">=3 char search string" },
      { name: "page", description: "Pagination cursor" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 2,
  },
  {
    key: "players.seasons",
    category: "players",
    path: "/players/seasons",
    description: "Seasons for which a given player has data.",
    params: [{ name: "player", description: "Player id" }],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
  {
    key: "players.squads",
    category: "players",
    path: "/players/squads",
    description: "Current squad list for a team, or the team(s) a player belongs to.",
    params: [
      { name: "team", description: "Team id" },
      { name: "player", description: "Player id" },
    ],
    tier: "semi-static",
    cacheTtlSeconds: 7 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 2,
  },
  {
    key: "players.teams",
    category: "players",
    path: "/players/teams",
    description: "All teams a player has played for, by season.",
    params: [{ name: "player", required: true, description: "Player id" }],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
  {
    key: "players.topscorers",
    category: "players",
    path: "/players/topscorers",
    description: "Top 20 goalscorers for a league+season.",
    params: [
      { name: "league", required: true, description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 3,
  },
  {
    key: "players.topassists",
    category: "players",
    path: "/players/topassists",
    description: "Top 20 assist providers for a league+season.",
    params: [
      { name: "league", required: true, description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 2,
  },
  {
    key: "players.topyellowcards",
    category: "players",
    path: "/players/topyellowcards",
    description: "Top 20 players by yellow cards for a league+season.",
    params: [
      { name: "league", required: true, description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 1,
  },
  {
    key: "players.topredcards",
    category: "players",
    path: "/players/topredcards",
    description: "Top 20 players by red cards for a league+season.",
    params: [
      { name: "league", required: true, description: "League id" },
      { name: "season", required: true, description: "4-digit season" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 1,
  },

  // ---- Transfers / Trophies / Sidelined --------------------------------------------------
  {
    key: "transfers",
    category: "transfers",
    path: "/transfers",
    description: "Transfer history for a player or a team.",
    params: [
      { name: "player", description: "Player id" },
      { name: "team", description: "Team id" },
    ],
    tier: "semi-static",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 1,
  },
  {
    key: "trophies",
    category: "trophies",
    path: "/trophies",
    description: "Trophies won by a player or a coach.",
    params: [
      { name: "player", description: "Player id (comma-separated for several)" },
      { name: "coach", description: "Coach id (comma-separated for several)" },
    ],
    tier: "semi-static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 1,
  },
  {
    key: "sidelined",
    category: "sidelined",
    path: "/sidelined",
    description: "Periods a player or coach was sidelined (injury/suspension), historical.",
    params: [
      { name: "player", description: "Player id" },
      { name: "coach", description: "Coach id" },
    ],
    tier: "semi-static",
    cacheTtlSeconds: 24 * 3600,
    vendorRecommendedCallsPerDay: 1,
    priority: 1,
  },

  // ---- Odds --------------------------------------------------------------------------------
  {
    key: "odds",
    category: "odds",
    path: "/odds",
    description: "Pre-match bookmaker odds, filterable by fixture, league, season, date or bookmaker.",
    params: [
      { name: "fixture", description: "Fixture id" },
      { name: "league", description: "League id" },
      { name: "season", description: "4-digit season" },
      { name: "date", description: "YYYY-MM-DD" },
      { name: "bookmaker", description: "Bookmaker id" },
      { name: "bet", description: "Bet type id" },
      { name: "page", description: "Pagination cursor" },
      { name: "timezone", description: "A valid timezone" },
    ],
    tier: "scheduled",
    cacheTtlSeconds: 6 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 2,
  },
  {
    key: "odds.mapping",
    category: "odds",
    path: "/odds/mapping",
    description: "Fixture ids for which pre-match odds exist.",
    params: [{ name: "page", description: "Pagination cursor" }],
    tier: "static",
    cacheTtlSeconds: 7 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
  {
    key: "odds.bookmakers",
    category: "odds",
    path: "/odds/bookmakers",
    description: "All bookmakers known to the API.",
    params: [
      { name: "id", description: "Bookmaker id" },
      { name: "search", description: "Search string" },
    ],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
  {
    key: "odds.bets",
    category: "odds",
    path: "/odds/bets",
    description: "All pre-match bet types known to the API (1X2, over/under, etc.).",
    params: [
      { name: "id", description: "Bet type id" },
      { name: "search", description: "Search string" },
    ],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
  {
    key: "odds.live",
    category: "odds",
    path: "/odds/live",
    description: "In-play odds, updated continuously while a fixture is live.",
    params: [
      { name: "fixture", description: "Fixture id" },
      { name: "league", description: "League id" },
      { name: "bet", description: "Bet type id" },
    ],
    tier: "live",
    cacheTtlSeconds: 30,
    vendorRecommendedCallsPerDay: null,
    priority: 2,
  },
  {
    key: "odds.live.bets",
    category: "odds",
    path: "/odds/live/bets",
    description: "All in-play bet types known to the API.",
    params: [
      { name: "id", description: "Bet type id" },
      { name: "search", description: "Search string" },
    ],
    tier: "static",
    cacheTtlSeconds: 30 * 24 * 3600,
    vendorRecommendedCallsPerDay: null,
    priority: 1,
  },
];

export const ENDPOINTS_BY_KEY: Record<string, EndpointDefinition> = Object.fromEntries(
  ENDPOINTS.map((e) => [e.key, e]),
);

export function getEndpoint(key: string): EndpointDefinition {
  const def = ENDPOINTS_BY_KEY[key];
  if (!def) {
    throw new Error(`Unknown football-agent endpoint key: "${key}"`);
  }
  return def;
}
